version: "3"
services:
  frontend:
    build:
      context: https://${TOKEN}@github.com/Filiq/sner-frontend.git#main
    ports:
      - "18080:18080"
    depends_on:
      - backend

  backend:
    build:
      context: .
    ports:
      - "18000:18000"
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sner

volumes:
  db-data:
