name: Tests CI
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: sudo apt-get install postgresql && sudo systemctl start postgresql
      - run: make install-deps
      - run: make install-extra
      - run: make db-create-test
      - run: make
      - run: make test-extra
